simple_job:
  script: echo "simple job"

on_msater:
  script: echo "on msater"
  only:
  - msater

on_hotfix:
  script: echo "on hotfix"
  only:
  - /^hotfix-/

by_tag:
  script: echo "by eny tag"
  only:
  - tags

by_message:
  script: echo "by message RUN TEST"
  only:
    variables:
    - $CI_COMMIT_MESSAGE == /RUN TEST/

expect_master:
  script: echo "not master"
  except:
  - master

manual:
  script: echo "manual"
  when: manual

on_push:
  script: echo "on push"
  only:
  - pushes

on_branches:
  script: echo "on branches"
  only:
  - branches

on_web:
  script: echo "on web"
  only:
  - web




